# Site settings
title: jbodah.github.io
email: jb3689@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Some guy's thoughts on Elixir, Ruby, and other things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jbodah.github.io" # the base hostname & protocol for your site
github_username:  jbodah

# Build settings
markdown: redcarpet

permalink: /blog/:year/:month/:day/:title/
