# Setup
title:               jbodah.github.io
tagline:             ''
description:         ''
url:                 https://jbodah.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Josh Bodah
  # url:               https://twitter.com/mdo
  email:             joshuabodah@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
